Run shellcheck in CI
Shellcheck lints shell scripts, helping to prevent common mistakes:
https://github.com/koalaman/shellcheck#gallery-of-bad-code

It would have caught the typo that was fixed in #161.

In order for shellcheck to pass, the following needed fixing:

- SC2006: Use $(...) notation instead of legacy backticks `...`.
          -> https://www.shellcheck.net/wiki/SC2006
- SC2046: Quote this to prevent word splitting.
          -> https://www.shellcheck.net/wiki/SC2046
- SC2048: Use "$@" (with quotes) to prevent whitespace problems.
          -> https://www.shellcheck.net/wiki/SC2048
- SC2068: Double quote array expansions to avoid re-splitting elements.
          -> https://www.shellcheck.net/wiki/SC2068
- SC2086: Double quote to prevent globbing and word splitting.
          -> https://www.shellcheck.net/wiki/SC2086

All non-sourced scripts have also been updated to use stricter bash modes:
http://redsymbol.net/articles/unofficial-bash-strict-mode/

Refs W-7496420.

diff --git a/tools/bin/update-manifest b/tools/bin/update-manifest
--- a/tools/bin/update-manifest
+++ b/tools/bin/update-manifest
@@ -1,8 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -e
+set -euo pipefail
 
-[ -z "$MANIFEST_APP_URL" ] && echo "Missing manifest app url" && exit 1
-[ -z "$MANIFEST_APP_TOKEN" ] && echo "Missing manifest app token" && exit 1
-
-exit 0
+[[ -v MANIFEST_APP_URL ]] || { echo "Missing manifest app url" && exit 1; }
+[[ -v MANIFEST_APP_TOKEN ]] || { echo "Missing manifest app token" && exit 1; }
